### ISSUE TITLE
Selecting Issues in GitHub Settings part of P1 Assignment repo setup.

### ISSUE THREAD

**Issue by jameslyleyoung** [LaunchCodeEducation/liftoff-assignments#198]
We need to add something to the effect:
Now that you have cloned the repo, and have your own remote repository, go to Github, select this repo, click on settings, and make sure you click the checkbox next to Issues.
It seems odd that this isn't apart of the assignment, seemings you want us, the TA's, to comment on Students' progress using GitHub Issues.

**Comment by pdmxdd** [comment]
This has been addressed by commit c1a3ed3
