### ISSUE TITLE
Order Section

### ISSUE THREAD

**Issue by darkboywonder** [LaunchCodeEducation/liftoff-assignments#38]
As a user, I should have access to an order section in which, I can view a form of all possible menu items available, their price and select quantity. As a user, I should be able to list my contact info and location for food to be delivered, or as a logged in user, this information is generated when I first open the form. I should also have a place for notes for the company to fill. This should be a form that upon submission, sends my order to STLGyros.com primary contact for the order to be completed.

optional:
- It can have a preview total

**Comment by amudalapalli123** [comment]
I will discuss with Kevin to add above requirements.

**Comment by darkboywonder** [comment]
Sweet.
