### ISSUE TITLE
Need Email Notification

### ISSUE THREAD

**Issue by darkboywonder** [LaunchCodeEducation/liftoff-assignments#39]
As a user, upon submission of my order, I expect to receive an email that my order was placed. I also expect stlgyros.com to also be notified via email.

**Comment by amudalapalli123** [comment]
Shawn,  I am going to discuss with Kevin to add the online ordering requirement to the project. If it is feasible to add in the current project then definitely i will add the order confirmation notification to the user will also be added.

**Comment by darkboywonder** [comment]
Awesome. Sounds good!
