### ISSUE TITLE
consistency in updating LEARNERS.md

### ISSUE THREAD

**Issue by MikeIsAnAsset** [LaunchCodeEducation/liftoff-assignments#59]
LEARNERS.md - I presume we are section 2?  I see the pull requests - everybody's done it slightly different.  I guess that'll be covered tonight.  Should I wait or do it now?  My thinking is to delete the old stuff on my own repo's LEARNERS.md and just put my info.  Thoughts? (edited)

1 reply
mikeIsAnAsset [2 hours ago]
*Per:*
https://help.github.com/articles/creating-a-pull-request-from-a-fork/

*I selected:*
Create a new branch for this commit and start a pull request. Learn more about pull requests.

*which defaulted to a:* GITHUB_USERNAME-patch-1 
branch name.  

I presume this is the _topic_branch in the aforementioned link?  Of the PR's that I've looked at on the LaunchCode repo, everybody's used their master branch as their compare branch, whereas I used what I think is this "topic" branch, defaulting to a name ending in -patch-1.  I did it this way in case I'm told later I need to change and make a new commit.

Is my thinking logical?

**Comment by pdmxdd** [comment]
Thanks for the feedback Mike. We have a solution moving forward which is creating a new LEARNERS.md file for each new class, and having stubbed out content for them.
